apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    run: litecoin
  name: litecoin-deploy
spec:
  replicas: 1
  serviceName: "litecoin"
  selector:
    matchLabels:
      run: litecoin
  template:
    metadata:
      labels:
        run: litecoin
    spec:
      volumes:
      - name: litecoin
        persistentVolumeClaim:
          claimName: pvc-nfs-pv1
      containers:
      - image: uphold/litecoin-core:0.18.1
        name: litecoin
        volumeMounts:
        - name: litecoin
          mountPath: /home/litecoin/.litecoin

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-pv1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs_server_ip
    path: "/mnt/nfs_share"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-pv1
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi